[project]
name = "prodexa"
version = "0.1.0"
description = "Open-source product intelligence desktop app"
license = { file = "LICENSE" }
authors = [{ name = "Ahmed" }]

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
prodexa = ["assets/**/*", "resources/**/*"]
